## ONE HOT ENCODING

In [1]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [2]:
from sklearn.preprocessing import OneHotEncoder
ohc = OneHotEncoder()
ohe = ohc.fit_transform(df.Temperature.values.reshape(-1,1)).toarray()
dfOneHot = pd.DataFrame(ohe, columns = ["Temp_"+str(ohc.categories_[0][i]) 
                                                for i in range(len(ohc.categories_[0]))])
dfh = pd.concat([df, dfOneHot], axis=1)
dfh

  Temperature   Color  Target  Temp_Cold  Temp_Hot  Temp_Very Hot  Temp_Warm
0         Hot     Red       1        0.0       1.0            0.0        0.0
1        Cold  Yellow       1        1.0       0.0            0.0        0.0
2    Very Hot    Blue       1        0.0       0.0            1.0        0.0
3        Warm    Blue       0        0.0       0.0            0.0        1.0
4         Hot     Red       1        0.0       1.0            0.0        0.0
5        Warm  Yellow       0        0.0       0.0            0.0        1.0
6        Warm     Red       1        0.0       0.0            0.0        1.0
7         Hot  Yellow       0        0.0       1.0            0.0        0.0
8         Hot  Yellow       1        0.0       1.0            0.0        0.0
9        Cold  Yellow       1        1.0       0.0            0.0        0.0

## LABEL ENCODING

In [3]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [4]:
from sklearn.preprocessing import LabelEncoder
df['Temp_label_encoded'] = LabelEncoder().fit_transform(df.Temperature)
df

  Temperature   Color  Target  Temp_label_encoded
0         Hot     Red       1                   1
1        Cold  Yellow       1                   0
2    Very Hot    Blue       1                   2
3        Warm    Blue       0                   3
4         Hot     Red       1                   1
5        Warm  Yellow       0                   3
6        Warm     Red       1                   3
7         Hot  Yellow       0                   1
8         Hot  Yellow       1                   1
9        Cold  Yellow       1                   0

## ORDINAL ENCODING

In [5]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [6]:
from sklearn.preprocessing import OrdinalEncoder
df['Temp_ordinal_encoded'] = OrdinalEncoder().fit_transform(df.Temperature.values.reshape(-1,1))
df

  Temperature   Color  Target  Temp_ordinal_encoded
0         Hot     Red       1                   1.0
1        Cold  Yellow       1                   0.0
2    Very Hot    Blue       1                   2.0
3        Warm    Blue       0                   3.0
4         Hot     Red       1                   1.0
5        Warm  Yellow       0                   3.0
6        Warm     Red       1                   3.0
7         Hot  Yellow       0                   1.0
8         Hot  Yellow       1                   1.0
9        Cold  Yellow       1                   0.0

## PANDAS GET_DUMMIES

In [7]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [8]:
df = pd.get_dummies(df, prefix=['Temp'], columns=['Temperature'])
df

    Color  Target  Temp_Cold  Temp_Hot  Temp_Very Hot  Temp_Warm
0     Red       1          0         1              0          0
1  Yellow       1          1         0              0          0
2    Blue       1          0         0              1          0
3    Blue       0          0         0              0          1
4     Red       1          0         1              0          0
5  Yellow       0          0         0              0          1
6     Red       1          0         0              0          1
7  Yellow       0          0         1              0          0
8  Yellow       1          0         1              0          0
9  Yellow       1          1         0              0          0

## TARGET ENCODING (MEAN ENCODING)

In [28]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
mean_encode = df.groupby('Temperature')['Target'].mean()
print(mean_encode)
df.loc[:, 'Temperature_mean_enc'] = df['Temperature'].map(mean_encode)
df

In [29]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Target'])

In [30]:
mean_encode = df.groupby('Temperature')['Target'].mean()
print(mean_encode)
df.loc[:, 'Temperature_mean_enc'] = df['Temperature'].map(mean_encode)
df

Temperature
Cold        1.000000
Hot         0.750000
Very Hot    1.000000
Warm        0.333333
Name: Target, dtype: float64

  Temperature  Target  Temperature_mean_enc
0         Hot       1              0.750000
1        Cold       1              1.000000
2    Very Hot       1              1.000000
3        Warm       0              0.333333
4         Hot       1              0.750000
5        Warm       0              0.333333
6        Warm       1              0.333333
7         Hot       0              0.750000
8         Hot       1              0.750000
9        Cold       1              1.000000

In [26]:
#encoded values from mean encoding
print(mean_encode)
#test data without the target
test_data = {'Temperature': ['Cold','Very Hot','Warm','Hot','Hot','Hot','Cold','Cold']}
dft = pd.DataFrame(test_data,columns = ['Temperature'])
#map temperature using map data for mean encoding created during training
dft['Temperature_mean_enc'] = dft['Temperature'].map(mean_encode)
dft

Temperature
Cold        1.000000
Hot         0.750000
Very Hot    1.000000
Warm        0.333333
Name: Target, dtype: float64

  Temperature  Temperature_mean_enc
0        Cold              1.000000
1    Very Hot              1.000000
2        Warm              0.333333
3         Hot              0.750000
4         Hot              0.750000
5         Hot              0.750000
6        Cold              1.000000
7        Cold              1.000000

## TARGET ENCODING (SMOOTHING)

In [11]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [12]:
# Compute the global mean
mean = df['Target'].mean()
# Compute the number of values and the mean of each group
agg = df.groupby('Temperature')['Target'].agg(['count', 'mean'])
counts = agg['count']
means = agg['mean']
weight = 100          
# Compute the 'smoothed' means
smooth = (counts * means + weight * mean) / (counts + weight)
# Replace each value by the according smoothed mean
print(smooth)
df.loc[:, 'Temperature_smean_enc'] = df['Temperature'].map(smooth)
df

Temperature
Cold        0.705882
Hot         0.701923
Very Hot    0.702970
Warm        0.689320
dtype: float64

  Temperature   Color  Target  Temperature_smean_enc
0         Hot     Red       1               0.701923
1        Cold  Yellow       1               0.705882
2    Very Hot    Blue       1               0.702970
3        Warm    Blue       0               0.689320
4         Hot     Red       1               0.701923
5        Warm  Yellow       0               0.689320
6        Warm     Red       1               0.689320
7         Hot  Yellow       0               0.701923
8         Hot  Yellow       1               0.701923
9        Cold  Yellow       1               0.705882

## FREQUENCY ENCODING

In [13]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [14]:
fe= df.groupby('Temperature').size()/len(df)
df.loc[:, 'Temp_freq_encode'] = df['Temperature'].map(fe)
df

  Temperature   Color  Target  Temp_freq_encode
0         Hot     Red       1               0.4
1        Cold  Yellow       1               0.2
2    Very Hot    Blue       1               0.1
3        Warm    Blue       0               0.3
4         Hot     Red       1               0.4
5        Warm  Yellow       0               0.3
6        Warm     Red       1               0.3
7         Hot  Yellow       0               0.4
8         Hot  Yellow       1               0.4
9        Cold  Yellow       1               0.2

## PANDAS FACTORIZE

In [15]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [16]:
df.loc[:, 'Temp_fatorize_encode'] = pd.factorize(df['Temperature'])[0].reshape(-1,1)
df

  Temperature   Color  Target  Temp_fatorize_encode
0         Hot     Red       1                     0
1        Cold  Yellow       1                     1
2    Very Hot    Blue       1                     2
3        Warm    Blue       0                     3
4         Hot     Red       1                     0
5        Warm  Yellow       0                     3
6        Warm     Red       1                     3
7         Hot  Yellow       0                     0
8         Hot  Yellow       1                     0
9        Cold  Yellow       1                     1

In [17]:
Ordinal — convert string labels to integer values 1 through k. Ordinal.
OneHot — one column for each value to compare vs. all other values. Nominal, ordinal.
Binary — convert each integer to binary digits. Each binary digit gets one column. Some info loss but fewer dimensions. Ordinal.
BaseN — Ordinal, Binary, or higher encoding. Nominal, ordinal. Doesn’t add much functionality. Probably avoid.
Hashing — Like OneHot but fewer dimensions, some info loss due to collisions. Nominal, ordinal.
Helmert (reverse) — The mean of the dependent variable for a level is compared to the mean of the dependent variable over all previous levels.
Sum — compares the mean of the dependent variable for a given level to the overall mean of the dependent variable over all the levels. 
Backward Difference — the mean of the dependent variable for a level is compared with the mean of the dependent variable for the prior level. 
Polynomial — orthogonal polynomial contrasts. The coefficients taken on by polynomial coding for k=4 levels are the linear, quadratic, and cubic trends in the categorical variable.
Target — use the mean of the DV, must take steps to avoid overfitting/ response leakage. Nominal, ordinal. For classification tasks.
LeaveOneOut — similar to target but avoids contamination. Nominal, ordinal. For classification tasks.
WeightOfEvidence — added in v1.3. Not documented in the docs as of April 11, 2019. The method is explained in this post.
James-Stein — forthcoming in v1.4. Described in the code here.
M-estimator — forthcoming in v1.4. Described in the code here. Simplified target encoder.

SyntaxError: invalid character in identifier (<ipython-input-17-726edb567949>, line 1)

## LABEL BINARIZER

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
tmp = lb.fit_transform(df.Temperature)
dfb = pd.DataFrame(tmp, columns = ["Temp_"+str(lb.classes_[i]) for i in range(len(lb.classes_))])
df = pd.concat([df, dfb], axis=1)
df

## POLYNOMIAL ENCODING

## BACKWARD DIFFERENCE ENCODING

In [ ]:
## Helmert Codin

In [ ]:
## Binary

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
import category_encoders as ce
encoder = ce.BinaryEncoder(cols=['Temperature'])
dfbin = encoder.fit_transform(df['Temperature'])
df = pd.concat([df, dfbin], axis=1)
df

## ORDINAL ENCODING

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
Temp_dict = { 'Cold' : 1,
              'Warm' : 2,
              'Hot' : 3,
              'Very Hot' :4}
df['Temp_Ordinal'] = df.Temperature.map(Temp_dict)
df

## HELMERT ENCODING

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
import category_encoders as ce
encoder = ce.HelmertEncoder(cols=['Temperature'],drop_invariant=True)
dfh = encoder.fit_transform(df['Temperature'])
df = pd.concat([df, dfh], axis=1)
df

### Weight of Evidance Encoding

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
# We calculate probablity of target = 1 i.e. Good = 1 for each category
woe_df = df.groupby('Temperature')['Target'].mean()
woe_df = pd.DataFrame(woe_df)
# Rename the column name to 'Good' to keep it consistent with formula for easy understanding
woe_df=  woe_df.rename(columns = {'Target':'Good'})
# Calculate Bad probabiliry which is 1- Good probability
woe_df['Bad'] = 1-woe_df.Good
# We need to add a small value to avoid divide by zero in denominator
woe_df['Bad'] = np.where(woe_df['Bad'] == 0, 0.000001, woe_df['Bad'])
# compute the WoE
woe_df['WoE'] = np.log(woe_df.Good/woe_df.Bad)
woe_df

In [ ]:
# Map the WOE values back to each row of data-frame
df.loc[:, 'WoE_Encode'] = df['Temperature'].map(woe_df['WoE'])
df

## Probability Ratio Encoding

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
# We calculate probablity of target = 1 i.e. Good = 1 for each category
pr_df = df.groupby('Temperature')['Target'].mean()
pr_df = pd.DataFrame(pr_df)
# Rename the column name to 'Good' to keep it consistent with formula for easy understanding
pr_df=  pr_df.rename(columns = {'Target':'Good'})
# Calculate Bad probabiliry which is 1- Good probability
pr_df['Bad'] = 1-pr_df.Good
# We need to add a small value to avoid divide by zero in denominator
pr_df['Bad'] = np.where(pr_df['Bad'] == 0, 0.000001, pr_df['Bad'])
# compute the Probability Ratio
pr_df['PR'] = pr_df.Good/pr_df.Bad
pr_df

In [ ]:
# Map the Probability Ratio values back to each row of data-frame
df.loc[:, 'PR_Encode'] = df['Temperature'].map(pr_df['PR'])
df

## Hashing Encoding

In [ ]:
import pandas as pd
import numpy as np
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

In [ ]:
# Map the Probability Ratio values back to each row of data-frame
df['Hash_Encode'] = df['Temperature'].apply(lambda x : hash(x))
df

## M-estimator categorical encoding

In [4]:
import pandas as pd
import numpy as np

# sample data
data = {'Temperature': ['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target': [1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data,columns = ['Temperature','Color','Target'])

# count the frequency of each category
category_counts = df['Temperature'].value_counts()

# calculate the weight for each category based on deviation from the mean frequency
weights = (category_counts - category_counts.mean()).abs()
weights = weights / weights.sum()

# create a dictionary to map each category to its weight
mapping = dict(zip(weights.index, weights.values))

# map the categories to their weights
df['weights'] = df['Temperature'].map(mapping)

# calculate weighted encoding for each category
encoded = df.groupby('Temperature')['weights'].sum()
encoded = encoded / encoded.sum()

# map the weighted encoding back to the categories
df['encoded_temperature'] = df['Temperature'].map(encoded)

In [6]:
df

  Temperature   Color  Target  weights  encoded_temperature
0         Hot     Red       1    0.375                 0.60
1        Cold  Yellow       1    0.125                 0.10
2    Very Hot    Blue       1    0.375                 0.15
3        Warm    Blue       0    0.125                 0.15
4         Hot     Red       1    0.375                 0.60
5        Warm  Yellow       0    0.125                 0.15
6        Warm     Red       1    0.125                 0.15
7         Hot  Yellow       0    0.375                 0.60
8         Hot  Yellow       1    0.375                 0.60
9        Cold  Yellow       1    0.125                 0.10

## Thermometer Encoder

In [10]:
import pandas as pd

# sample data
data = {'color': ['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow']}
df = pd.DataFrame(data)

# get the unique categories and their ranks
categories = df['color'].unique()
ranks = range(len(categories))

# create a dictionary to map each category to its rank
mapping = dict(zip(categories, ranks))

# map the categories to their ranks
df['ranks'] = df['color'].map(mapping)

# create the thermometer encoding for each category
encoded = pd.get_dummies(df['ranks'])
encoded = encoded.add_prefix('thermometer_')

# merge the encoding with the original data
df = pd.concat([df, encoded], axis=1)

df

    color  ranks  thermometer_0  thermometer_1  thermometer_2
0     Red      0              1              0              0
1  Yellow      1              0              1              0
2    Blue      2              0              0              1
3    Blue      2              0              0              1
4     Red      0              1              0              0
5  Yellow      1              0              1              0
6     Red      0              1              0              0
7  Yellow      1              0              1              0
8  Yellow      1              0              1              0
9  Yellow      1              0              1              0